export const root: string;
export const inputWrapper: string;
export const input: string;
export const background: string;
export const checkmark: string;
export const checkmarkPath: string;
export const mixedMark: string;
export const ripple: string;
export const disabled: string;
